### ISSUE TITLE
opera 28 on linux can't be started by ate

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#108] opened 2015-04-22 19:43 UTC
I tried to run script with operadriver, but I got the following error.
It seems that driver couldn't find opera binary. I just installed the opera v28 on my linux though.

Peidong
=============
12:24:47.103 [main] ERROR o.b.ate.systemlogger.LogbackWriter - SYS_LOG: Test-Error: org.bigtester.ate.model.page.atewebdriver.MyOperaDriver@14b31e37org.openqa.selenium.WebDriverException: unknown error: cannot find Opera binary
  (Driver info: OperaDriver beta=0.1 (87cdb4f0d742fb950d1f0fca1f3f6b483e4fb69c),platform=Linux 3.13.0-32-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 776 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'ubuntu_file_lap', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-32-generic', java.version: '1.8.0_11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:160)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:117)
	at org.bigtester.ate.model.page.atewebdriver.MyOperaDriver.getWebDriverInstance(MyOperaDriver.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)

**Comment by Jun-Yang** [comment] 2015-04-22 20:30
The problem is the path of opera is not correct. So the dirver cannnot find
opera binary.

2015-04-22 16:43 GMT-03:00 Peidong Hu <notifications@github.com>:

**Comment by peidong-hu** [comment] 2015-04-23 07:58
how could I fix it? as I have seen on this page, https://code.google.com/p/selenium/wiki/OperaDriver, operadriver seems only support up to opera 12. I am using opera28, does it matter?

**Comment by Jun-Yang** [comment] 2015-04-23 12:53
Now we use the chromium driver, not the operaprestodriver.

https://github.com/operasoftware/operachromiumdriver. It support
chromium-based versions of Opera starting from version 26.

You can install the opera in the following path:

The OperaDriver server expects you to have Opera or Opera Next installed in
the default location for each system:
*OS* *Expected Location of Opera* GNU/Linux /usr/bin/opera

/usr/bin/opera-next

/usr/bin/operamobile Mac /Applications/Opera.app/Contents/MacOS/Opera

/Applications/Opera Next.app/Contents/MacOS/Opera

/Applications/Opera Mobile Emulator.app/Contents/Resources/Opera
Mobile.app/Contents/MacOS/operamobile Windows %PROGRAMFILES%\Opera\opera.exe

%PROGRAMFILES%\Opera Next\opera.exe

%PROGRAMFILES%\Opera Mobile Emulator\OperaMobileEmu.exe

2015-04-23 4:58 GMT-03:00 Peidong Hu <notifications@github.com>:

**Comment by peidong-hu** [comment] 2015-04-23 14:49
I got this on my ubuntu, it seems that opera is in the right folder,
==============
peidong@ubuntu_file_lap:/usr/bin$ ls -l opera
lrwxrwxrwx 1 root root 35 Apr  3 16:07 opera -> ../lib/x86_64-linux-gnu/opera/opera
peidong@ubuntu_file_lap:/usr/bin$

**Comment by Jun-Yang** [comment] 2015-04-29 00:34
I dont have 64Bits ubuntu. Can you test it again? 
I think you should install opera in /usr/bin/opera. Please try it again.

**Comment by peidong-hu** [comment] 2015-04-29 00:56
We r going to leave it for future to resolve.

**Comment by Jun-Yang** [comment] 2015-05-15 04:20
Fixed by set the opera binary path in chrome options

**Closed by Jun-Yang** 2015-05-15 04:20 UTC
Labels: medium prioirty
